USE [master]
GO

/****** Object:  Database [octap]    Script Date: 11/11/2020 9:14:07 AM ******/
CREATE DATABASE [octap]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OCTAP', FILENAME = N'F:\sqldata\OCTAP.mdf' , SIZE = 232384KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'OCTAP_log', FILENAME = N'E:\sqldata\OCTAP_1.ldf' , SIZE = 7168KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [octap] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [octap].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [octap] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [octap] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [octap] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [octap] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [octap] SET ARITHABORT OFF 
GO

ALTER DATABASE [octap] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [octap] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [octap] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [octap] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [octap] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [octap] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [octap] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [octap] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [octap] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [octap] SET  DISABLE_BROKER 
GO

ALTER DATABASE [octap] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [octap] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [octap] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [octap] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [octap] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [octap] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [octap] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [octap] SET RECOVERY FULL 
GO

ALTER DATABASE [octap] SET  MULTI_USER 
GO

ALTER DATABASE [octap] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [octap] SET DB_CHAINING OFF 
GO

ALTER DATABASE [octap] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [octap] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [octap] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [octap] SET QUERY_STORE = OFF
GO

USE [octap]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [octap] SET  READ_WRITE 
GO

